
export const SPECIALITYLIST: string[] = [
    "Médecine du comportement des animaux domestiques",
    "Médecine interne des animaux de compagnie",
    "Médecine interne des animaux de compagnie, option cardiologie",
    "Anatomie pathologique vétérinaire",
    "Chirurgie des animaux de compagnie",
    "Chirurgie équine",
    "Dermatologie vétérinaire",
    "Elevage et pathologie des équidés",
    "Gestion de la santé des bovins",
    "Gestion de la santé et de la qualité en productions avicoles",
    "Gestion de la santé et de la qualité en production laitière",
    "Gestion de la santé et de la qualité en production porcine",
    "Imagerie médicale vétérinaire",
    "Médecine interne des équidés",
    "Neurologie vétérinaire",
    "Nutrition clinique vétérinaire",
    "Ophtalmologie vétérinaire",
    "Pathologie clinique vétérinaire",
    "Santé et productions animales en régions chaudes",
    "Santé publique vétérinaire - sciences des aliments",
    "Santé publique vétérinaire - médecine des populations",
    "Sciences et médecine des animaux de laboratoire",
    "Stomatologie et dentisterie vétérinaires"
  ];
